### ISSUE TITLE
Set up gathering@innersourcecommons.org address

### ISSUE THREAD

**Issue by yuhattor** [InnerSourceCommons/gatherings#18]
I would like to set up gathering@innersourcecommons.org mail address

**Comment by bory-kb** [comment]
@rrrutledge @andrea-kyurchiev 

I would like to receive inquiries through the contact page on the gathering event website. 
I will display the following email address on the contact page. 
gathering@innersourcecommons.org
Could you assist me?

FYI : @yuhattor

**Comment by andrea-kyurchiev** [comment]
Hi @bory-kb there already is a gathering**s**@innersourcecommons.org so if you could display that instead that would be great. If you can provide me with your email address I can add you to the group and you will be able to see and respond to inquiries received at that address

**Comment by bory-kb** [comment]
Thank you!!
I will send you my email address on Slack.

**Comment by yuhattor** [comment]
Thank you @andrea-kyurchiev and @bory-kb !!
