### ISSUE TITLE
Domain configuration for the gathering site

### ISSUE THREAD

**Issue by yuhattor** [InnerSourceCommons/gatherings#2]
@HK3330 
https://innersourcecommons.github.io/gathering/ のページについて
gatherings.innersourcecommons.github.io にドメインをセットしたいです。

以下の 2 人にドメインの設定の依頼をすることは出来ますでしょうか??
- rrrutledge, andrea-kyurchiev

**Comment by bory-kb** [comment]
👇の Issue で対応するのでいったんこちらは Close にします。
https://github.com/InnerSourceCommons/gatherings/issues/18

**Comment by bory-kb** [comment]
Hi, @rrrutledge @andrea-kyurchiev 

I would like to set up a custom domain for the website of the gathering event held in japan, whitch is currently hosted on GitHub Pages.
Could you assist me with this? 
The website is currently available at the following URL:
https://innersourcecommons.github.io/gatherings/

I would like to use gatherings.innersourcecommons.org as the custom domain for this site. 

FYI : @yuhattor

**Comment by HK3330** [comment]
@bory-kb 
こちらに進捗かけてなくてすみません。

同じやりとりしちゃってたらすみません。

<img width="1045" alt="image" src="https://github.com/InnerSourceCommons/gatherings/assets/37994618/2936b471-ad3a-4b3c-8720-030c132669ba">


<img width="949" alt="image" src="https://github.com/InnerSourceCommons/gatherings/assets/37994618/0c099a58-cc97-4813-b320-17ba4d10fffe">

**Comment by bory-kb** [comment]
GitHub Pages にカスタムドメインを設定して無事に閲覧できるようになったのでこのIssueはクローズにします。

https://gatherings.innersourcecommons.org/tokyo-2024/
