### ISSUE TITLE
セッション募集特番の開催

### ISSUE THREAD

**Issue by bory-kb** [InnerSourceCommons/gatherings#26]
- [ ] : 開催するかどうか考える（スピーカー募集チームと連携）

---

![Image](https://github.com/InnerSourceCommons/gatherings/assets/15963767/9669271b-8bc5-4b03-afab-20064141a3de)

**Comment by bory-kb** [comment]
スピーカーチームのミーティングの結果、CfPの形を取らないので特番の立ち位置を見直す必要あり。

**Comment by yuhattor** [comment]
一端クローズします！
