### ISSUE TITLE
CFP の概要

### ISSUE THREAD

**Issue by HK3330** [InnerSourceCommons/gatherings#28]
- [ ] : サイトに反映させる

---

Call for Proposal の説明: 
InnerSource Gatheringでは、技術、ケーススタディ、組織内外の活動に関するセッションスピーカーを募集中です。

**Comment by HK3330** [comment]
https://innersourcecommons.slack.com/archives/C06GYRW4Q6P/p1712567353451559?thread_ts=1712122139.873519&cid=C06GYRW4Q6P

> 今日やったこと
> １日のスケジュール感を検討
> https://miro.com/app/board/uXjVKbUnrA8=/
> 半日で 基調講演 ＋ セッション６個ぐらい ＋ OST の想定
> 登壇者候補リスト作成
> スケジュール感みたところセッション枠も多くないのでCfPで公募しない方針に
> https://docs.google.com/spreadsheets/d/1pF6uWzljLcNtU5M8fIFVLaPQnUuTRWsV66oo5e7np5A/edit#gid=0
> :上向き指差し_2:のシートに聞いてみたい・話してくれそうな人をリストアップ。推しポイントとかを記入する担当を割り振りした （次回プランニングの 4/18 にまでに埋める）


CfPで公募しない方針にとなったので、掲載不要になりましたかね？

**Comment by bory-kb** [comment]
CfPで公募しない方針になりましたのでこの Issue は Close します。
