### ISSUE TITLE
Listing Organizers / オーガナイザーのリストをページに追加

### ISSUE THREAD

**Issue by yuhattor** [InnerSourceCommons/gatherings#3]
以下のようにオーガナイザーの顔写真 / アイコン/SNSリンクを掲載したい
![Image](https://github.com/InnerSourceCommons/gatherings/assets/15963767/f2974055-c211-4b47-b0a1-e28a5743369b)

- [ ] オーガナイザー全員の写真やアイコン, SNSリンクを掲載
- [ ] ページを更新 (必要に応じて @yuhattor メンションしてください🙏)

**Comment by bory-kb** [comment]
👇の Issue が同様の内容でそちらで対応するので Close にします。
https://github.com/InnerSourceCommons/gatherings/issues/30
