### ISSUE TITLE
© InnerSource Gathering Tokyo executive committee

### ISSUE THREAD

**Issue by HK3330** [InnerSourceCommons/gatherings#30]

**Comment by HK3330** [comment]
これはどこを修正すればいいのだろう。

こことは別かな？
![Image](https://github.com/InnerSourceCommons/gatherings/assets/37994618/44857b94-6ce5-49f3-91ff-f73a5b4b53ed)

**Comment by jimmysharp** [comment]
<img width="1256" alt="スクリーンショット 2024-04-25 17 06 11" src="https://github.com/InnerSourceCommons/gatherings/assets/10284531/81517976-a5e9-44d1-bb57-79aca936fdca">

多分そこの下ですね
copyright©︎の後が何も書かれていないので

**Comment by HK3330** [comment]
organizerを追加しようとしたらすでに服部さんがやっていそう。
なので、コピーライトだけPR出します。
<img width="461" alt="image" src="https://github.com/InnerSourceCommons/gatherings/assets/37994618/e0370928-800e-4e9e-9d6f-1d363e2dc81b">

**Comment by yuhattor** [comment]
ありがとうございます！

**Comment by yuhattor** [comment]
すみません、先にやっちゃいました！
