### ISSUE TITLE
事例ピックアップ

### ISSUE THREAD

**Issue by HK3330** [InnerSourceCommons/gatherings#31]
- [ ] : 事例をピックアップし、事例元となる会社に連絡（？）して載せていいか確認する

---

![Image](https://github.com/InnerSourceCommons/gatherings/assets/15963767/f3c4aed0-59c5-4544-bec4-cd0e41d33ec4)

**Comment by HK3330** [comment]
これはblogのページを変えていけば良さそうな気がする。

![Image](https://github.com/InnerSourceCommons/gatherings/assets/37994618/f9b8412a-baaa-4f59-aaa5-b48b226d9a70)

**Comment by HK3330** [comment]
https://innersourcecommons.slack.com/archives/C06GYRW4Q6P/p1713350017702799?thread_ts=1712115130.215199&cid=C06GYRW4Q6P
> そうですね！
> Panasonic とか、メルカリ, Line とか、CyberAgent の記事で、名前が有名なものをいくつかピックアップするのが良いかもです。
> (もちろん Nifty さんブログも)

有名なものをピックアップしてみる。

**Comment by HK3330** [comment]
- Panasonic
  - https://news.mynavi.jp/techplus/kikaku/azure_case_td-254/
  - 同じか？ https://customers.microsoft.com/ja-jp/story/1653141783429229154-panasonic-manufacturing-azure-ja-jp
- メルカリ
  - https://github.co.jp/customer-stories/mercari
- CyberAgent
  -  [Dグレード制度](https://developers.cyberagent.co.jp/blog/archives/38992/) 
  - [Development Inner Sourcing](https://speakerdeck.com/cyberagentdevelopers/100wochao-erukai-fa-timufalseji-shu-qing-bao-lian-xi-woshi-xian-suru-ca-base-next) 
  -  [サイバーエージェントのインナーソース事例](https://developers.cyberagent.co.jp/blog/archives/43038/)
- ニフティ
  - https://engineering.nifty.co.jp/blog/22132

- 気になる点
  - 企業が直接出している記事じゃないと、媒体にさらに許可？そして、媒体の宣伝になっちゃう？

**Comment by HK3330** [comment]
服部さん、久保さんに相談しました。

> Shoma Kubo
>   1日前
> ピックアップする記事は InnerSource Commons Webサイトの事例一覧に乗ってる日本企業のリンクでいいかなって思ってました！
> ４つ５つぐらいだと思うので全部載せちゃってもいいかなーって。
> @Yuki Hattori
> 
> Commons のWebサイトに載ってるので今回の Gathering 用にわざわざ許可もらう必要ないと思ってますがどうですかね？


> Yuki Hattori
>   1日前
> キャッチアップ遅れてスミマセン！
> 明日飛行機の中でキャッチアップします！
> はい、コモンズのWebサイトに載っているのが良いと思います！
> 許可済みなはずなので
> これを期に許可を取っちゃうのもいいかなとは思ったりしました

コモンズのWebサイトに乗っていれば再度許可を取るのは不要、４，５記事くらいということで、一旦それで進めます。

追加の記事は＋αでできれば。

**Comment by HK3330** [comment]
事例紹介のところで、記事クリックするとサブページがでるけど、もう直接事例ページに飛ばすようにしてしまうか。

コモンズのページにあったもの
- メルカリ
  - https://github.com/customer-stories/mercari
- ニフティ
  - https://engineering.nifty.co.jp/blog/22132
- パナソニックコネクト
  - https://customers.microsoft.com/ja-jp/story/1653141783429229154-panasonic-manufacturing-azure-ja-jp
- 東芝
  - イベントのページか
  - https://eventyay.com/e/3dbaaa50


タイトルと企業名とリンクだけの記事を作った。
<img width="587" alt="image" src="https://github.com/InnerSourceCommons/gatherings/assets/37994618/7420b735-6989-4375-bbe8-0cf9471d10db">

**Comment by yuhattor** [comment]
返信遅れてスミマセン
それかもしかしたら、記事にしちゃったほうがいいですかね?? 🤔

**Comment by HK3330** [comment]
この前の定例会でもうリンク集ぐらいのレベルでいいかもという話があったので、一旦それで公開できるところまで目指します。

**Comment by yuhattor** [comment]
お願いします！
